version: '3.6'

services:
  db:
    image: postgres:11.6
    command: postgres -c fsync=${FSYNC:-off} -c max_connections=200
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  base:
    image: "${IMAGE_BASE}overhave-base:${POETRY_CONTENT_HASH:-unset}"
    build:
      context: .
      dockerfile: docker/Dockerfile.base
      network: host
      args:
        DOCKER_HUB_PROXY: "${DOCKER_HUB_PROXY}"
  code:
    image: "${IMAGE_BASE}overhave:${BUILD_NUMBER:-unset}"
    build:
      context: .
      dockerfile: docker/Dockerfile.code
      network: host
      args:
        IMAGE_BASE: "${IMAGE_BASE}"
        POETRY_CONTENT_HASH: "${POETRY_CONTENT_HASH:-unset}"
    environment:
      - OVERHAVE_DB_URL=${OVERHAVE_DB_URL:-postgresql://postgres:postgres@db/postgres}
      - OVERHAVE_REDIS_URL=${OVERHAVE_REDIS_URL:-redis://redis:6379}
      - OVERHAVE_REDIS_SENTINEL_URLS=${OVERHAVE_REDIS_SENTINEL_URLS:-["redis://redis:6379"]}
      - PACKAGE_BUILD_DIR=${PACKAGE_BUILD_DIR:-.package/dist}
    depends_on:
      - db
      - redis

  publish:
    build:
      context: .
      dockerfile: docker/Dockerfile.publish
      network: host
      args:
        IMAGE_BASE: "${IMAGE_BASE}"
        BUILD_NUMBER: "${BUILD_NUMBER:-unset}"
    environment:
      - PYPI_TOKEN=${PYPI_TOKEN:-unset}
      - VENV=${VENV:-.tox/.package}
