# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.12"
    
      - name: Run a multi-line script
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        # set `export PYTHON_VERSION=` since python3.10 cause not working with ver
        run: |
          export PYTHON_VERSION=3
          sudo apt-get update
          make pre-init
          make init
          make publish
